title: Aviatrix | AWS Immersion Day
author: Aviatrix | AWS Immersion Day
copyright: "2024"
logo: "../docs/_logos/aviatrix-logo.svg"

# Short description about the book
description: >-
  Aviatrix | AWS Immersion Day Lab Guide

execute:
  execute_notebooks: off

# HTML-specific settings
html:
  home_page_in_navbar: true
  favicon: "../docs/_logos/aviatrix-favicon-32.png"
