title: Aviatrix Automation - Instructor Led
author: Aviatrix ACE
copyright: "2024"
logo: "../docs/_logos/aviatrix-logo.svg"

# Short description about the book
description: >-
  Aviatrix ACE Automation Lab Guide

execute:
  execute_notebooks: off

# HTML-specific settings
html:
  home_page_in_navbar: true
  favicon: "../docs/_logos/aviatrix-favicon-32.png"
